/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMsgItem: typeof import('./components/ChatMsgItem/ChatMsgItem.vue')['default']
    VAvatar: typeof import('./components/VAvatar/VAvatar.vue')['default']
    VBadge: typeof import('./components/VBadge/VBadge.vue')['default']
    VDivider: typeof import('./components/VDivider/VDivider.vue')['default']
    VIcon: typeof import('./components/VIcon/VIcon.vue')['default']
    VImage: typeof import('./components/VImage/VImage.vue')['default']
    VListItem: typeof import('./components/VListItem/VListItem.vue')['default']
    VNavbar: typeof import('./components/VNavbar/VNavbar.vue')['default']
    VPopup: typeof import('./components/VPopup/VPopup.vue')['default']
  }
}
