/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VAvatar: typeof import('./components/VAvatar/VAvatar.vue')['default']
    VBadge: typeof import('./components/VBadge/VBadge.vue')['default']
    VNavbar: typeof import('./components/VNavbar/VNavbar.vue')['default']
  }
}
